= Hacktoberfest 2024: Solicitud de Apoyo
Equipo Hacktoberfest <gye@hacktoberfest.com>; Olga Tohabanda <olga@gmail.com>; Brayen Gavilanes <brayen@gmail.com>

Aquí debe ir una carta presentando la iniciativa del Hacktoberfest.

== Hacktoberfest 2024

Tenemos que explicar sobre el Hacktoberfest.

== Comunidades organizadoras

include::../organizadores/organizadores.adoc[]

== ¿Por qué nosotros?

== ¿Qué ofrecemos?

Aquí, encontrará una tabla que detalla los niveles de patrocinio disponibles:

[%autowidth.stretch]
|===
|Nivel de Auspicio |Monto |Beneficios

|Diamante
|$350 o más
|Reconocimiento destacado como auspiciador principal al inicio, intermedios y final del evento. +
Logotipo de su organización en los materiales promocionales. +
Mención especial en nuestras redes sociales y sitio web. +
Oportunidad de colocar 2 RollUps y material publicitario.

|Oro
|$300
|Reconocimiento destacado como auspiciador principal al inicio y final del evento. +
Logotipo de su organización en los materiales promocionales. +
Mención en nuestras redes sociales y sitio web. +
Oportunidad de colocar 1 RollUp y material publicitario.

|Plata
|$250
|Reconocimiento destacado como auspiciador principal al inicio y final del evento. +
Mención en nuestras redes sociales. +
Logotipo de su organización en los materiales promocionales. +
Oportunidad de colocar material publicitario.

| Bronce
| $100
| * Reconocimiento como auspiciador en el evento. +
* Logotipo de su organización en los materiales promocionales. +
* Mención en nuestras redes sociales.
|===
